# Generated by Django 5.2.11 on 2026-02-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('deadline_days', models.PositiveIntegerField()),
                ('estimated_hours', models.FloatField()),
                ('importance', models.IntegerField(default=1)),
                ('priority_score', models.FloatField(default=0)),
                ('priority_category', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
